registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt  //在docker swarm中以service方式运行需要这个，参看https://docs.docker.com/registry/deploying/#use-an-insecure-registry-testing-only
    REGISTRY_HTTP_TLS_KEY: /certs/domain.key //在docker swarm中以service方式运行需要这个，参看https://docs.docker.com/registry/deploying/#use-an-insecure-registry-testing-only
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
    - ~/registry/data:/var/lib/registry
    - ~/registry/certs:/certs
    - ~/registry/auth:/auth
    
    
 运行命令docker-compose up -d
 
 image: registry:2默认使用https链接     获得证书的方法请参考
 https://docs.docker.com/registry/deploying/#get-a-certificate
 测试不安全的注册表   部署纯HTTP注册表  使用自签名证书 排除不安全的注册表
 https://docs.docker.com/registry/insecure/#deploying-a-plain-http-registry
